name: dns_configurator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  build_runner: ^2.4.11
  connectivity_plus: ^6.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  freezed: ^2.5.2
  get_it: ^8.0.2
  mocktail: ^1.0.4
  shared_preferences: ^2.3.3
  test: ^1.25.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
